package ua.goit.module.tenth.task5;

public class SecondException extends Exception{
}
